# Adds namespace to all resources.
namespace: ${NAMESPACE}

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: external-routing-

resources:
- manager.yaml
- rbac.yaml
- leader_election_role_binding.yaml
- leader_election_role.yaml